apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest  # Use the Grafana Docker image version you prefer
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          envFrom:
            - configMapRef:
                name: grafana-config
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
